main: de.linzn.stemLinkBridge.StemLinkBridgePlugin
name: stemLink-bridge
version: ${project.version}
depend: [ home-devices ]
buildJobName: ${buildServer.jobName}
buildNumber: ${buildServer.buildNumber}